version: '3.9'

services:

  postgresql:
    container_name: postgresql
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: peliculas_db
    volumes:
      - postgreslq:/var/lib/postgresql/data
    ports:
      - 5432:5432

  pgadmin4:
    container_name: pgadmin4
    image: dpage/pgadmin4
    restart: always
    environment:
        PGADMIN_DEFAULT_EMAIL: admin@admin.com
        PGADMIN_DEFAULT_PASSWORD: admin
    volumes:
      - pgadmin:/var/lib/pgadmin
    ports:
      - 5050:80

  monogdb:
    container_name: mongodb
    image: mongo
    restart: always
    environment: 
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: admin
    volumes:
      - mongo:/data/db
    ports:
      - 27017:27017

volumes:
  postgreslq:
  pgadmin:
  mongo: